name: Prod-Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  forecasts-deployment:
    runs-on: self-hosted
    steps:
      - name: Prod-Deploy
        working-directory: /var/www/html/jucar
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          git pull origin main
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          bun upgrade
          composer run build
